// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "传递温情的蓝丝带";

const lessonData = [
    // ===== 第1段 =====
    ["美国", "měi guó", "America", "Amerika"],
    ["一个", "yī gè", "a", "sebuah"],
    ["乡村", "xiāng cūn", "village", "kampung"],
    ["小镇", "xiǎo zhèn", "small town", "pekan kecil"],
    ["流传", "liú chuán", "spread", "tersebar"],
    ["着", "zhe", "", ""],
    ["这么", "zhè me", "such", "begitu"],
    ["一个", "yī gè", "a", "satu"],
    ["故事", "gù shì", "story", "cerita"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["即将", "jí jiāng", "about to", "akan"],
    ["卸下", "xiè xià", "step down from", "melepaskan"],
    ["教职", "jiào zhí", "teaching post", "jawatan guru"],
    ["的", "de", "", ""],
    ["萨宾娜", "sà bīn nà", "Sabina", "Sabina"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["想着", "xiǎng zhe", "thinking", "berfikir"],
    ["还", "hái", "still", "masih"],
    ["能", "néng", "can", "boleh"],
    ["为", "wèi", "for", "untuk"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["做", "zuò", "do", "buat"],
    ["点什么", "diǎn shén me", "something", "sesuatu"],
    ["。", "", "", ""],
    ["不一会儿", "bù yī huì ér", "soon", "tidak lama kemudian"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["走向", "zǒu xiàng", "walk towards", "berjalan ke arah"],
    ["书桌", "shū zhuō", "desk", "meja tulis"],
    ["，", "", "", ""],
    ["拉开", "lā kāi", "pull open", "menarik"],
    ["了", "le", "", ""],
    ["抽屉", "chōu tì", "drawer", "laci"],
    ["，", "", "", ""],
    ["拿起", "ná qǐ", "pick up", "mengambil"],
    ["搁在", "gē zài", "placed at", "terletak di"],
    ["里头", "lǐ tou", "inside", "di dalam"],
    ["的", "de", "", ""],
    ["四根", "sì gēn", "four", "empat"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["了", "le", "", ""],
    ["从小", "cóng xiǎo", "since childhood", "sejak kecil"],
    ["被", "bèi", "by", "oleh"],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["抛弃", "pāo qì", "abandoned", "ditinggalkan"],
    ["的", "de", "", ""],
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["——", "", "", ""],
    ["别人", "bié rén", "others", "orang lain"],
    ["眼中", "yǎn zhōng", "eyes", "mata"],
    ["的", "de", "", ""],
    ["问题学生", "wèn tí xué shēng", "problem student", "pelajar bermasalah"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["萨宾娜", "sà bīn nà", "Sabina", "Sabina"],
    ["曾经", "céng jīng", "once", "pernah"],
    ["看到", "kàn dào", "see", "melihat"],
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["救起", "jiù qǐ", "rescued", "menyelamatkan"],
    ["受伤", "shòu shāng", "injured", "cedera"],
    ["的", "de", "", ""],
    ["小松鼠", "xiǎo sōng shǔ", "little squirrel", "tupai kecil"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["想", "xiǎng", "want", "mahu"],
    ["帮帮", "bāng bāng", "help", "menolong"],
    ["这个", "zhè gè", "this", "ini"],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["有爱", "yǒu ài", "has love", "ada kasih"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["第二天", "dì èr tiān", "next day", "hari berikutnya"],
    ["，", "", "", ""],
    ["萨宾娜", "sà bīn nà", "Sabina", "Sabina"],
    ["把", "bǎ", "", ""],
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["叫到", "jiào dào", "called to", "dipanggil ke"],
    ["办公室", "bàn gōng shì", "office", "pejabat"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["拿出", "ná chū", "take out", "mengeluarkan"],
    ["那", "nà", "those", "itu"],
    ["四根", "sì gēn", "four", "empat"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["的", "de", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["，", "", "", ""],
    ["温柔", "wēn róu", "gently", "lembut"],
    ["且", "qiě", "and", "dan"],
    ["徐徐", "xú xú", "slowly", "perlahan"],
    ["地", "de", "", ""],
    ["说", "shuō", "say", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["保罗", "bǎo luó", "Paul", "Paul"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["我", "wǒ", "I", "saya"],
    ["小时候", "xiǎo shí hou", "childhood", "zaman kanak-kanak"],
    ["，", "", "", ""],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["送给", "sòng gěi", "gave", "memberi"],
    ["我", "wǒ", "me", "saya"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["说", "shuō", "said", "berkata"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["会", "huì", "will", "akan"],
    ["带着", "dài zhe", "carry", "membawa"],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["爱", "ài", "love", "kasih"],
    ["和", "hé", "and", "dan"],
    ["祝福", "zhù fú", "blessing", "berkat"],
    ["，", "", "", ""],
    ["一生", "yī shēng", "lifetime", "seumur hidup"],
    ["守护", "shǒu hù", "protect", "melindungi"],
    ["着", "zhe", "", ""],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["我", "wǒ", "my", "saya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["之一", "zhī yī", "one of", "salah satu"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "jadi"],
    ["我", "wǒ", "I", "saya"],
    ["将", "jiāng", "", ""],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["最", "zuì", "most", "paling"],
    ["宝贵", "bǎo guì", "precious", "berharga"],
    ["的", "de", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["你", "nǐ", "you", "awak"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "dalam"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["遇到", "yù dào", "encounter", "menghadapi"],
    ["太多", "tài duō", "too many", "terlalu banyak"],
    ["的", "de", "", ""],
    ["不公平", "bù gōng píng", "unfairness", "ketidakadilan"],
    ["和", "hé", "and", "dan"],
    ["伤害", "shāng hài", "hurt", "kecederaan"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["你", "nǐ", "you", "awak"],
    ["有爱", "yǒu ài", "has love", "ada kasih"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["你", "nǐ", "you", "awak"],
    ["能", "néng", "can", "boleh"],
    ["挺过", "tǐng guò", "endure", "harungi"],
    ["一切", "yī qiè", "all", "segala"],
    ["风雨", "fēng yǔ", "storms", "badai"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["你", "nǐ", "you", "awak"],
    ["有", "yǒu", "have", "ada"],
    ["能力", "néng lì", "ability", "keupayaan"],
    ["将", "jiāng", "", ""],
    ["诚恳", "chéng kěn", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["爱", "ài", "love", "kasih"],
    ["传递", "chuán dì", "pass on", "menyampaikan"],
    ["给", "gěi", "to", "kepada"],
    ["更多", "gèng duō", "more", "lebih banyak"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["。", "", "", ""],
    ["你", "nǐ", "You", "Awak"],
    ["保留", "bǎo liú", "keep", "simpan"],
    ["一根", "yī gēn", "one", "satu"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membiarkan"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["爱", "ài", "love", "kasih"],
    ["和", "hé", "and", "dan"],
    ["力量", "lì liàng", "strength", "kekuatan"],
    ["守护", "shǒu hù", "protect", "melindungi"],
    ["你", "nǐ", "you", "awak"],
    ["。", "", "", ""],
    ["另外", "lìng wài", "in addition", "selain itu"],
    ["三根", "sān gēn", "three", "tiga"],
    ["就", "jiù", "then", "lalu"],
    ["传出去", "chuán chū qù", "pass on", "sampaikan"],
    ["，", "", "", ""],
    ["照亮", "zhào liàng", "illuminate", "menyinari"],
    ["其他", "qí tā", "other", "lain"],
    ["生命", "shēng mìng", "lives", "kehidupan"],
    ["吧", "ba", "", ""],
    ["！”", "", "", ""],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["说", "shuō", "said", "berkata"],
    ["的", "de", "", ""],
    ["话", "huà", "words", "kata-kata"],
    ["让", "ràng", "made", "membuat"],
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["感到", "gǎn dào", "feel", "merasa"],
    ["满心", "mǎn xīn", "full of heart", "penuh hati"],
    ["的", "de", "", ""],
    ["温暖", "wēn nuǎn", "warmth", "kehangatan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["，", "", "", ""],
    ["思考", "sī kǎo", "think", "berfikir"],
    ["着", "zhe", "", ""],
    ["该", "gāi", "should", "patut"],
    ["把", "bǎ", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["谁", "shuí", "who", "siapa"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["了", "le", "", ""],
    ["邻居", "lín jū", "neighbour", "jiran"],
    ["——", "", "", ""],
    ["半工半读", "bàn gōng bàn dú", "work-study", "bekerja sambil belajar"],
    ["的", "de", "", ""],
    ["大学生", "dà xué shēng", "university student", "pelajar universiti"],
    ["罗恩", "luó ēn", "Ron", "Ron"],
    ["哥哥", "gē ge", "brother", "abang"],
    ["。", "", "", ""],
    ["罗恩", "luó ēn", "Ron", "Ron"],
    ["最近", "zuì jìn", "recently", "kebelakangan ini"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["工作", "gōng zuò", "work", "kerja"],
    ["压力", "yā lì", "pressure", "tekanan"],
    ["大", "dà", "big", "besar"],
    ["而", "ér", "and", "dan"],
    ["情绪", "qíng xù", "emotion", "emosi"],
    ["低落", "dī luò", "low", "murung"],
    ["。", "", "", ""],
    ["小保罗", "xiǎo bǎo luó", "Little Paul", "Paul Kecil"],
    ["向", "xiàng", "to", "kepada"],
    ["他", "tā", "him", "dia"],
    ["讲述", "jiǎng shù", "narrate", "menceritakan"],
    ["了", "le", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["的", "de", "", ""],
    ["由来", "yóu lái", "origin", "asal usul"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["将", "jiāng", "", ""],
    ["三根", "sān gēn", "three", "tiga"],
    ["丝带", "sī dài", "ribbons", "riben"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["给了", "gěi le", "gave", "memberi"],
    ["他", "tā", "him", "dia"],
    ["力量", "lì liàng", "strength", "kekuatan"],
    ["和", "hé", "and", "dan"],
    ["勇气", "yǒng qì", "courage", "keberanian"],
    ["。", "", "", ""],
    ["随后", "suí hòu", "afterwards", "selepas itu"],
    ["，", "", "", ""],
    ["罗恩", "luó ēn", "Ron", "Ron"],
    ["将", "jiāng", "", ""],
    ["两根", "liǎng gēn", "two", "dua"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["给了", "gěi le", "gave", "memberi"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["雷恩", "léi ēn", "Ryan", "Ryan"],
    ["，", "", "", ""],
    ["感谢", "gǎn xiè", "thank", "berterima kasih"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["给了", "gěi le", "gave", "memberi"],
    ["他", "tā", "him", "dia"],
    ["工作", "gōng zuò", "job", "kerja"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["对", "duì", "to", "bagi"],
    ["他", "tā", "him", "dia"],
    ["而言", "ér yán", "for", "bagi"],
    ["是", "shì", "is", "ialah"],
    ["莫大", "mò dà", "greatest", "terbesar"],
    ["的", "de", "", ""],
    ["恩惠", "ēn huì", "favour", "kurnia"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["向", "xiàng", "to", "kepada"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["承诺", "chéng nuò", "promise", "berjanji"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["会", "huì", "will", "akan"],
    ["和", "hé", "with", "dengan"],
    ["老板", "lǎo bǎn", "boss", "bos"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["渡过难关", "dù guò nán guān", "overcome difficulties", "mengharungi kesukaran"],
    ["。", "", "", ""],
    ["深受", "shēn shòu", "deeply", "sangat"],
    ["感动", "gǎn dòng", "moved", "terharu"],
    ["的", "de", "", ""],
    ["雷恩", "léi ēn", "Ryan", "Ryan"],
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["将", "jiāng", "", ""],
    ["其中", "qí zhōng", "among", "di antaranya"],
    ["一根", "yī gēn", "one", "satu"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["了", "le", "", ""],
    ["女儿", "nǚ ér", "daughter", "anak perempuan"],
    ["。", "", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["的", "de", "", ""],
    ["故事", "gù shì", "story", "cerita"],
    ["就", "jiù", "then", "lalu"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["在", "zài", "in", "di"],
    ["社区", "shè qū", "community", "komuniti"],
    ["里", "lǐ", "in", "dalam"],
    ["一传十", "yī chuán shí", "spread from one to ten", "tersebar dari satu ke sepuluh"],
    ["，", "", "", ""],
    ["十传百", "shí chuán bǎi", "spread from ten to a hundred", "tersebar dari sepuluh ke seratus"],
    ["，", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["传遍", "chuán biàn", "spread throughout", "tersebar ke seluruh"],
    ["了", "le", "", ""],
    ["整个", "zhěng gè", "whole", "seluruh"],
    ["小镇", "xiǎo zhèn", "small town", "pekan kecil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["后来", "hòu lái", "Later", "Kemudian"],
    ["，", "", "", ""],
    ["一个", "yī gè", "a", "seorang"],
    ["名叫", "míng jiào", "named", "bernama"],
    ["海莉思", "hǎi lì sī", "Helice", "Helice"],
    ["的", "de", "", ""],
    ["美国", "měi guó", "American", "Amerika"],
    ["妇女", "fù nǚ", "woman", "wanita"],
    ["创造", "chuàng zào", "created", "mencipta"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["一分钟", "yī fēn zhōng", "one minute", "satu minit"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["颁奖仪式", "bān jiǎng yí shì", "award ceremony", "upacara anugerah"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["借此", "jiè cǐ", "thereby", "dengan itu"],
    ["来", "lái", "to", "untuk"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["她", "tā", "her", "dia"],
    ["对", "duì", "to", "terhadap"],
    ["人们", "rén men", "people", "orang ramai"],
    ["的", "de", "", ""],
    ["赞美", "zàn měi", "praise", "pujian"],
    ["和", "hé", "and", "dan"],
    ["感谢", "gǎn xiè", "gratitude", "kesyukuran"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["不分", "bù fēn", "regardless of", "tanpa mengira"],
    ["年龄", "nián líng", "age", "umur"],
    ["、", "", "", ""],
    ["种族", "zhǒng zú", "race", "kaum"],
    ["、", "", "", ""],
    ["宗教", "zōng jiào", "religion", "agama"],
    ["或者", "huò zhě", "or", "atau"],
    ["社会地位", "shè huì dì wèi", "social status", "status sosial"],
    ["，", "", "", ""],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["都", "dōu", "all", "semua"],
    ["需要", "xū yào", "need", "perlu"],
    ["得到", "dé dào", "receive", "mendapat"],
    ["肯定", "kěn dìng", "affirmation", "pengiktirafan"],
    ["、", "", "", ""],
    ["尊重", "zūn zhòng", "respect", "menghormati"],
    ["以及", "yǐ jí", "and", "serta"],
    ["赞许", "zàn xǔ", "approval", "persetujuan"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["买了", "mǎi le", "bought", "membeli"],
    ["一千条", "yī qiān tiáo", "one thousand", "seribu"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["送给", "sòng gěi", "give to", "beri kepada"],
    ["身边", "shēn biān", "beside", "sisi"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["，", "", "", ""],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["谢意", "xiè yì", "gratitude", "kesyukuran"],
    ["。", "", "", ""],
    ["两个", "liǎng gè", "two", "dua"],
    ["星期", "xīng qī", "weeks", "minggu"],
    ["内", "nèi", "within", "dalam"],
    ["，", "", "", ""],
    ["就", "jiù", "already", "sudah"],
    ["有", "yǒu", "have", "ada"],
    ["一千人", "yī qiān rén", "one thousand people", "seribu orang"],
    ["收到", "shōu dào", "received", "menerima"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["。", "", "", ""],
    ["很快", "hěn kuài", "quickly", "cepat"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["在", "zài", "in", "di"],
    ["校园", "xiào yuán", "campus", "kampus"],
    ["和", "hé", "and", "dan"],
    ["社区", "shè qū", "community", "komuniti"],
    ["发挥", "fā huī", "exert", "memainkan"],
    ["了", "le", "", ""],
    ["效应", "xiào yìng", "effect", "kesan"],
    ["：", "", "", ""],
    ["学生", "xué shēng", "students", "pelajar"],
    ["的", "de", "", ""],
    ["成绩", "chéng jì", "results", "keputusan"],
    ["改善", "gǎi shàn", "improved", "bertambah baik"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["少年", "shào nián", "youths", "remaja"],
    ["的", "de", "", ""],
    ["自信", "zì xìn", "confidence", "keyakinan diri"],
    ["增强", "zēng qiáng", "increased", "meningkat"],
    ["了", "le", "", ""],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["从", "cóng", "From", "Daripada"],
    ["以上", "yǐ shàng", "above", "di atas"],
    ["两个", "liǎng gè", "two", "dua"],
    ["实例", "shí lì", "examples", "contoh"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["不难", "bù nán", "not difficult", "tidak sukar"],
    ["发现", "fā xiàn", "discover", "menemui"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["传达", "chuán dá", "convey", "menyampaikan"],
    ["了", "le", "", ""],
    ["一个", "yī gè", "a", "satu"],
    ["讯息", "xùn xī", "message", "mesej"],
    ["：", "", "", ""],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["其", "qí", "their", "ia"],
    ["可贵", "kě guì", "valuable", "berharga"],
    ["之处", "zhī chù", "aspect", "aspek"],
    ["，", "", "", ""],
    ["值得", "zhí dé", "worth", "layak"],
    ["他人", "tā rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["重视", "zhòng shì", "value", "menghargai"],
    ["和", "hé", "and", "dan"],
    ["尊重", "zūn zhòng", "respect", "menghormati"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["应", "yīng", "should", "harus"],
    ["不吝于", "bù lìn yú", "not stingy in", "tidak kedekut"],
    ["对", "duì", "to", "terhadap"],
    ["别人", "bié rén", "others", "orang lain"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["感激", "gǎn jī", "gratitude", "kesyukuran"],
    ["与", "yǔ", "and", "dan"],
    ["赞美", "zàn měi", "praise", "pujian"],
    ["。", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["我们", "wǒ men", "we", "kita"],
    ["得到", "dé dào", "receive", "mendapat"],
    ["夸奖", "kuā jiǎng", "praise", "pujian"],
    ["和", "hé", "and", "dan"],
    ["肯定", "kěn dìng", "affirmation", "pengiktirafan"],
    ["，", "", "", ""],
    ["会", "huì", "will", "akan"],
    ["对", "duì", "to", "terhadap"],
    ["自己", "zì jǐ", "oneself", "diri sendiri"],
    ["充满", "chōng mǎn", "full of", "penuh"],
    ["信心", "xìn xīn", "confidence", "keyakinan"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["自然", "zì rán", "naturally", "secara semula jadi"],
    ["学会", "xué huì", "learn", "belajar"],
    ["去", "qù", "to", "untuk"],
    ["欣赏", "xīn shǎng", "appreciate", "menghargai"],
    ["他人", "tā rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["优点", "yōu diǎn", "strengths", "kelebihan"],
    ["，", "", "", ""],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["更", "gèng", "more", "lebih"],
    ["容易", "róng yì", "easy", "mudah"],
    ["去", "qù", "to", "untuk"],
    ["称赞", "chēng zàn", "praise", "memuji"],
    ["别人", "bié rén", "others", "orang lain"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["去年", "qù nián", "last year", "tahun lepas"],
    ["教师节", "jiào shī jié", "Teachers' Day", "Hari Guru"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["将", "jiāng", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["慎重", "shèn zhòng", "carefully", "dengan berhati-hati"],
    ["地", "de", "", ""],
    ["别在", "bié zài", "pinned on", "disematkan pada"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["的", "de", "", ""],
    ["衣服", "yī fu", "clothes", "baju"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["有者", "yǒu zhě", "some", "sesetengah"],
    ["给予", "jǐ yǔ", "give", "memberi"],
    ["嘉许", "jiā xǔ", "commendation", "pujian"],
    ["，", "", "", ""],
    ["有者", "yǒu zhě", "some", "sesetengah"],
    ["给予", "jǐ yǔ", "give", "memberi"],
    ["鼓励", "gǔ lì", "encouragement", "galakan"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["他们", "tā men", "them", "mereka"],
    ["知道", "zhī dào", "know", "tahu"],
    ["他们", "tā men", "they", "mereka"],
    ["在", "zài", "in", "dalam"],
    ["我", "wǒ", "my", "saya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["带来", "dài lái", "brought", "membawa"],
    ["的", "de", "", ""],
    ["改变", "gǎi biàn", "change", "perubahan"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["在", "zài", "when", "apabila"],
    ["收到", "shōu dào", "received", "menerima"],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["露出", "lù chū", "showed", "menunjukkan"],
    ["了", "le", "", ""],
    ["惊喜", "jīng xǐ", "pleasant surprise", "kejutan gembira"],
    ["、", "", "", ""],
    ["羞涩", "xiū sè", "shyness", "malu"],
    ["、", "", "", ""],
    ["开心", "kāi xīn", "happy", "gembira"],
    ["等", "děng", "etc", "dan lain-lain"],
    ["表情", "biǎo qíng", "expressions", "ekspresi"],
    ["。", "", "", ""],
    ["往后", "wǎng hòu", "afterwards", "selepas itu"],
    ["的", "de", "", ""],
    ["日子", "rì zi", "days", "hari-hari"],
    ["里", "lǐ", "in", "di"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["了", "le", "", ""],
    ["不同", "bù tóng", "different", "berbeza"],
    ["程度", "chéng dù", "degree", "tahap"],
    ["的", "de", "", ""],
    ["改变", "gǎi biàn", "change", "perubahan"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["开始", "kāi shǐ", "start", "mula"],
    ["学会", "xué huì", "learn", "belajar"],
    ["发现", "fā xiàn", "discover", "menemui"],
    ["别人", "bié rén", "others", "orang lain"],
    ["的", "de", "", ""],
    ["优点", "yōu diǎn", "strengths", "kelebihan"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["令", "lìng", "make", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["倍感", "bèi gǎn", "especially feel", "sangat merasa"],
    ["欣慰", "xīn wèi", "gratified", "lega"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["我们", "wǒ men", "We", "Kita"],
    ["不妨", "bù fáng", "might as well", "tidak salah"],
    ["效仿", "xiào fǎng", "emulate", "mencontohi"],
    ["海莉思", "hǎi lì sī", "Helice", "Helice"],
    ["女士", "nǚ shì", "lady", "puan"],
    ["的", "de", "", ""],
    ["方式", "fāng shì", "way", "cara"],
    ["，", "", "", ""],
    ["送出", "sòng chū", "give out", "memberi keluar"],
    ["有形", "yǒu xíng", "tangible", "nyata"],
    ["或", "huò", "or", "atau"],
    ["无形", "wú xíng", "intangible", "tidak nyata"],
    ["的", "de", "", ""],
    ["蓝丝带", "lán sī dài", "blue ribbon", "riben biru"],
    ["，", "", "", ""],
    ["主动", "zhǔ dòng", "actively", "secara aktif"],
    ["地", "de", "", ""],
    ["向", "xiàng", "to", "kepada"],
    ["人", "rén", "people", "orang"],
    ["表达", "biǎo dá", "express", "menyatakan"],
    ["谢意", "xiè yì", "gratitude", "kesyukuran"],
    ["或", "huò", "or", "atau"],
    ["真诚", "zhēn chéng", "sincerely", "dengan ikhlas"],
    ["地", "de", "", ""],
    ["称许", "chēng xǔ", "praise", "memuji"],
    ["他人", "tā rén", "others", "orang lain"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membiarkan"],
    ["善", "shàn", "goodness", "kebaikan"],
    ["的", "de", "", ""],
    ["能量", "néng liàng", "energy", "tenaga"],
    ["在", "zài", "in", "di"],
    ["人群", "rén qún", "crowd", "orang ramai"],
    ["中", "zhōng", "in", "dalam"],
    ["传递", "chuán dì", "pass on", "menyampaikan"],
    ["。", "", "", ""],
    ["倘若", "tǎng ruò", "if", "jika"],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semua"],
    ["能", "néng", "can", "boleh"],
    ["互相", "hù xiāng", "mutually", "saling"],
    ["赞美", "zàn měi", "praise", "memuji"],
    ["和", "hé", "and", "dan"],
    ["感恩", "gǎn ēn", "grateful", "bersyukur"],
    ["，", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["社会", "shè huì", "society", "masyarakat"],
    ["将", "jiāng", "will", "akan"],
    ["呈现", "chéng xiàn", "present", "menunjukkan"],
    ["出", "chū", "", ""],
    ["一片", "yī piàn", "a", "satu"],
    ["祥和", "xiáng hé", "peaceful", "aman damai"],
    ["与", "yǔ", "and", "dan"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["的", "de", "", ""],
    ["氛围", "fēn wéi", "atmosphere", "suasana"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
